### ISSUE TITLE
broken link to indoor maps API

### ISSUE THREAD

**Issue by boblaublaw** [eegeo/eegeo-poi-api#2]
The link in the Readme points to:

https://github.com/wrld3d/indoor-map-api

but the working URL is: 

https://github.com/wrld3d/wrld-indoor-maps-api

**Comment by jonty-dawson** [comment]
Thanks for the report Joe, fixed with https://github.com/wrld3d/wrld-poi-api/commit/ea701b35e24f67588bfeef08e23a0a6aff1321b2
